# Variables

# Logo key. Use Mod1 for Alt and Mod4 for Super.
set $mod Mod4
set $alt_mod Mod1

# Direction keys
    set $left Left
    set $down Down
    set $up Up
    set $right Right

# Alternative direction keys (Vim like)
    set $left_alt h
    set $down_alt j
    set $up_alt k
    set $right_alt l

# Background
set $background ~/Pictures/wallpaper/background.*

# Background lockscreen
set $background_lockscreen ~/Pictures/wallpaper/background_lockscreen.*

# Onscreen bar (WOB)
set $WOBSOCK /tmp/wobpipe
set $wob rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob

# Audio control (wireplumber)
    set $sink_volume wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g'
    # Volume
    set $volume_down (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > $WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $WOBSOCK)
    set $volume_up (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > $WOBSOCK) || (wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $WOBSOCK)
    set $volume_mute wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > $WOBSOCK) || wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $WOBSOCK
    # Source
    set $source_mute wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Player control (playerctl)
set $player_pause playerctl pause
set $player_play_pause_toggle playerctl play-pause
set $player_next playerctl next
set $player_previous playerctl previous

# Brightness control
    set $brightness_down exec brightnessctl set 3%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK
    set $brightness_up exec brightnessctl set +3% | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK

# Screenshot
    set $grimshot /usr/share/sway/scripts/grimshot

    # Save screen to clipboard
    set $screenshot_screen exec $grimshot --notify copy screen
    # Save screen to file
    set $screenshot_screen_to_file $grimshot --notify save screen
    # Save selection to clipboard
    set $screenshot_selection $grimshot --notify copy area
    # Save selection to clipboard
    set $screenshot_selection_to_file $grimshot --notify save area

# Lockscreen configuration
    set $locking swaylock -f -i $background_lockscreen

# Idle configuration
set $locking_timeout 300
set $screen_timeout 600
set $sleep_timeout 900

set $swayidle swayidle -w \
    timeout $locking_timeout '$locking' \
    timeout $screen_timeout 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
    timeout $sleep_timeout 'swaymsg "output * dpms on"; systemctl suspend' \
    before-sleep '$locking' \
    before-sleep '$player_pause'

# Set GTK theme
    set $gtk_theme ~/dotfiles/scripts/gtk.sh

# Default apps
    # Terminal
    set $term alacritty
    # Audio control
    set $audio_control $term -e pulsemixer
    # Bluetooth manager
    set $bluetooth_manager $term -e bluetuith
    # Calendar
    set $calendar $term -e calcurse
    # File-Manager
    set $file_manager thunar
    # Menu
    set $menu fuzzel
    # Network manager
    set $network_manager $term -e nmtui
    # Resource monitor
    set $resource_monitor $term -e btop
