# Get app_id's with "swaymsg -t get_tree

# Borders
# Workaround to get rid of the titlebar
default_border pixel 3
hide_edge_borders --i3 smart

# Fonts
font pango:Sans Regular 12

# Gaps
# Set gaps thickness
gaps inner 3
gaps outer 3
# don't show gaps if there's only one window on the desktop
smart_gaps on

# set floating mode for specific applications
#for_window [app_id="pavucontrol"] floating enable

# inhibit idle
for_window [app_id="LibreWolf"] inhibit_idle fullscreen
