# Exec
# Init swayidle
set $swayidle swayidle -w \
    timeout $locking_timeout "$locking" \
    timeout $screen_timeout 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
    timeout $sleep_timeout "$suspend" \
    before-sleep "$locking" \
    after-resume 'swaymsg "output * dpms on"'

# Exec always
# Set GTK theme
set $gtk_theme /usr/local/bin/gtk.sh

# WOB
set $wob rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob
